### ISSUE TITLE
Symbolic links error

### ISSUE THREAD

**Issue by lukehedger** [thymikee/linaria-jest#2]
What's the reason for doing this https://github.com/thymikee/linaria-jest/blob/master/package.json#L11?

I think it might be causing an NPM error.

To replicate, install `linaria-jest` and then try to install any other package:
```sh
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/example/node_modules/linaria-jest/node_modules/linaria/npm-shrinkwrap.json'
```

**Comment by thymikee** [comment]
Oh yea, this is only for development. Mind fixing that? I think it should be changed to `prepare`

**Comment by lukehedger** [comment]
I'm not sure you need to run `yarn link linaria`, even in local development - as `linaria` is installed as a `dependency`?
