### ISSUE TITLE
How to test styled.* components?

### ISSUE THREAD

**Issue by miuirussia** [thymikee/linaria-jest#4]
When I try to test these components, I get an error:
```
Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly
```

**Comment by thymikee** [comment]
Unfortunately this project is not compatible with `linaria@1.x`. 
cc @satya164

**Comment by satya164** [comment]
Hey! You should need to test those components since you don't have any logic in them. But you should add he babel preset to be able to use those components in your tests as mentioned here: https://github.com/callstack/linaria#setup
